language: generic
python: ["3.7.3"]
install:
  - pip install --upgrade pip
  - pip install --upgrade pipenv
cache: pip
script:
  - yarn --cwd web install
  - yarn --cwd web build
  - docker build . -t pr-game:latest