language: generic
dist: bionic
before_install:
  - sudo apt-get update
  - sudo apt-get install python3-pip python3-setuptools
  - pip3 install --user pipenv
install:
  - pipenv install --dev --deploy
cache: pip
before_script:
  - isort --check-only *
  - flake8 --max-line-length=88 ./
  - black --check ./
script:
  - yarn --cwd web install
  - yarn --cwd web build
  - docker build . -t pr-game:latest
